[project]
name = "vision-assistant"
version = "0.1.0"
description = "PyQt5 Vision Assistant Application"
requires-python = ">=3.8"
dependencies = [
    "PyQt5",
    "anthropic[bedrock,vertex]>=0.37.1",
    "pillow",
    "pyyaml>=6.0.1",
    "platformdirs>=4.1.0",
    "qt-material",
]

[project.gui-scripts]
vision-assistant = "vision_assistant.main:main"
welcome = "welcome.main:main"

[project.scripts]
vision-assistant = "vision_assistant.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/vision_assistant"]
