[project]
name = "vision-assistant"
version = "0.1.0"
description = "Vision assistant using Claude's computer vision capabilities"
dependencies = [
    "anthropic-sdk",
    "pillow",
    "PyQt5",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
