name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential debhelper devscripts dh-python python3-all python3-setuptools python3-hatchling python3-pyqt5 python3-yaml python3-pillow python3-platformdirs nodejs npm qttools5-dev-tools

      - name: Build Debian package
        run: dpkg-buildpackage -us -uc

      - name: Move Debian packages
        run: |
          mkdir -p artifacts
          mv ../*.deb artifacts/
          mv ../*.buildinfo artifacts/
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: debian-packages
          path: artifacts/
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/*.deb
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
