name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Debian package
        run: |
          docker build -t builder -f docker/Dockerfile.build .
          docker run --rm -v ${{ github.workspace }}:/build builder dpkg-buildpackage -us -uc
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ../*.deb
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
